services:
  pgdatabase:
    container_name: "postgres_db"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=instacart
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - pg-network    

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    restart: always
    depends_on:
      - pgdatabase
    ports:
      - "8080:80"
    networks:
      - pg-network
  
  data_loader:
    build: ./data_loader  # Path to the Python Dockerfile
    container_name: data_loader
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    depends_on:
      - pgdatabase
    networks:
      - pg-network
  
  bronze_data_extractor:
    build: ./bronze
    container_name: bronze_data_extractor
    depends_on:
      - pgdatabase
    networks:
      - pg-network

networks:
  pg-network:
    name: pg-network

volumes:
  pg_data: